### ISSUE TITLE
it doesn't work, im trying to get it tell me that i know the RTK kanji lol

### ISSUE THREAD

**Issue by smarlitos** [tsudoko/kanjigrid#15]
Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue on the add-on support site.
Debug info:
Anki 2.1.26 (70784154) Python 3.8.0 Qt 5.13.1 PyQt 5.14.1
Platform: Mac 10.16
Flags: frz=True ao=True sv=1
Add-ons, last update check: 2020-12-31 20:59:18
Add-ons possibly involved: ⁨Kanji Grid⁩

Caught exception:
Traceback (most recent call last):
  File "/Users/carlosgonzalez/Library/Application Support/Anki2/addons21/909972618/Kanji_grid.py", line 457, in setup
    self.makegrid(config)
  File "/Users/carlosgonzalez/Library/Application Support/Anki2/addons21/909972618/Kanji_grid.py", line 362, in makegrid
    self.displaygrid(config, units, timeNow)
  File "/Users/carlosgonzalez/Library/Application Support/Anki2/addons21/909972618/Kanji_grid.py", line 280, in displaygrid
    self.generate(config, units, timeNow)
  File "/Users/carlosgonzalez/Library/Application Support/Anki2/addons21/909972618/Kanji_grid.py", line 256, in generate
    self.html += "<h4 style=\"color:#888;\">%d of %d - %0.2f%%</h4>\n" % (n, gc, n*100.0/gc)
ZeroDivisionError: float division by zero

**Comment by vermouthmjl** [comment]
Hi @smarlitos 
I fixed this error in a fork and shared it on the [Anki website](https://ankiweb.net/shared/info/970930173).
Feel free to take a look.

**Comment by smarlitos** [comment]
Thank you so much!!! I really appreciate your help and hard work!

Warm Regards,
Carlos Gonzalez

**Comment by vermouthmjl** [comment]
Hi @smarlitos !
So happy that your bug is fixed by the fork. If you like the fork, I'd really appreciate if you could put in an upvote on [Anki](https://ankiweb.net/shared/info/970930173). It would make it easier to find for others ^^
Thanks !

**Comment by Tenome** [comment]
> Hi @smarlitos ! So happy that your bug is fixed by the fork. If you like the fork, I'd really appreciate if you could put in an upvote on [Anki](https://ankiweb.net/shared/info/970930173). It would make it easier to find for others ^^ Thanks !

Does this work on the current ⁨2.1.63 qt6 Anki? I installed your version and don't see the menu option like the previous Kanji Grid.

**Comment by smarlitos** [comment]
No, it doesn't seem to work.I got the old one to work, though.On May 24, 2023, at 12:53 PM, Tenome ***@***.***> wrote:Hi @smarlitos ! So happy that your bug is fixed by the fork. If you like the fork, I'd really appreciate if you could put in an upvote on Anki. It would make it easier to find for others ^^ Thanks !Does this work on the current ⁨2.1.63 qt6 Anki? I installed your version and don't see the menu option like the previous Kanji Grid.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>
